closedverse/urls.py
from django.conf.urls import url, include

from django.contrib import admin
from .settings import INSTALLED_APPS

handler500 = 'closedverse_main.views.server_err'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('closedverse_main.urls'))
]

if 'silk' in INSTALLED_APPS:
	urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

closedverse_main/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from django.shortcuts import redirect

from . import views
from closedverse.settings import MEDIA_URL, MEDIA_ROOT

username = r'(?P<username>[A-Za-z0-9-\'-._ ]+)'
community = r'(?P<community>[0-9]+)'
post = r'(?P<post>[0-9]+)'
comment = r'(?P<comment>[0-9]+)'
uuidr = r'[0-9a-f\-]'

app_name = 'main'

urlpatterns = [
	# Root
	url(r'^^$|^communities$|^index.*$$', views.community_list, name='community-list'),
	# Accounts
	url(r'login/$', views.login_page, name='login'),
	url(r'signup/$', views.signup_page, name='signup'),
	url(r'reset/$', views.forgot_passwd, name='forgot-passwd'),
	url(r'logout/$', views.logout_page, name='logout'),
	# User pages
	url(r'users/'+ username +'/manager$', views.user_manager, name='user-manager'),
	url(r'users/'+ username +'/follow$', views.user_follow, name='user-follow'),
	url(r'users/'+ username +'/unfollow$', views.user_unfollow, name='user-unfollow'),
	url(r'users/'+ username +'$', views.user_view, name='user-view'),
	url(r'users/'+ username +'/posts$', views.user_posts, name='user-posts'),
	url(r'users/'+ username +'/yeahs$', views.user_yeahs, name='user-yeahs'),
	url(r'users/'+ username +'/comments$', views.user_comments, name='user-comments'),
	url(r'users/'+ username +'/following$', views.user_following, name='user-following'),
	url(r'users/'+ username +'/followers$', views.user_followers, name='user-followers'),
	url(r'users/'+ username +'/friends$', views.user_friends, name='user-friends'),
	# User page friends
	url(r'users/'+ username +'/friend_new$', views.user_friendrequest_create, name='user-fr-create'),
	url(r'users/'+ username +'/friend_accept$', views.user_friendrequest_accept, name='user-fr-accept'),
	url(r'users/'+ username +'/friend_reject$', views.user_friendrequest_reject, name='user-fr-reject'),
	url(r'users/'+ username +'/friend_cancel$', views.user_friendrequest_cancel, name='user-fr-cancel'),
	url(r'users/'+ username +'/friend_delete$', views.user_friendrequest_delete, name='user-fr-delete'),

	url(r'users/'+ username +'/block$', views.user_addblock, name='user-addblock'),
	# Communities
	url(r'communities.search$', views.community_search, name='community-search'),
	url(r'communities/'+ community +'$', views.community_view, name='community-view'),
	url(r'communities/favorites$', views.community_favorites, name='community-favorites'),
	url(r'communities/all$', views.community_all, name='community-viewall'),
	url(r'communities/(?P<tag>[a-z]+)$', views.special_community_tag, name='special-community-tag'),
	url(r'communities/'+ community +'/favorite$', views.community_favorite_create, name='community-favorite-add'),
	url(r'communities/'+ community +'/favorite_rm$', views.community_favorite_rm, name='community-favorite-rm'),
	url(r'communities/'+ community +'/posts$', views.post_create, name='post-create'),
	# Posts and comments
	# Some of these NAMES (not patterns) are hardcoded into models.py
	url(r'posts/'+ post +'$', views.post_view, name='post-view'),
	url(r'posts/'+ post +'/yeah$', views.post_add_yeah, name='post-add-yeah'),
	url(r'posts/'+ post +'/yeahu$', views.post_delete_yeah, name='post-delete-yeah'),
	url(r'posts/'+ post +'/comments$', views.post_comments, name='post-comments'),
	url(r'posts/'+ post +'/comments$', views.post_comments, name='post-comments'),
	url(r'posts/'+ post +'/change$', views.post_change, name='post-change'),
	url(r'posts/'+ post +'/profile$', views.post_setprofile, name='post-set-profile'),
	url(r'posts/'+ post +'/profile_rm', views.post_unsetprofile, name='post-unset-profile'),
	url(r'posts/'+ post +'\.rm$', views.post_rm, name='post-rm'),
	url(r'comments/'+ comment +'$', views.comment_view, name='comment-view'),
	url(r'comments/'+ comment +'/yeah$', views.comment_add_yeah, name='comment-add-yeah'),
	url(r'comments/'+ comment +'/yeahu$', views.comment_delete_yeah, name='comment-delete-yeah'),
	url(r'comments/'+ comment +'/change$', views.comment_change, name='comment-change'),
	url(r'comments/'+ comment +'/rm$', views.comment_rm, name='comment-rm'),
	# Post-meta: polls
	url(r'poll/(?P<poll>'+ uuidr +'+)/vote$', views.poll_vote, name='poll-vote'),
	url(r'poll/(?P<poll>'+ uuidr +'+)/unvote$', views.poll_unvote, name='poll-unvote'),

	# Notifications
	url(r'alive$', views.check_notifications, name='check-notifications'),
	url(r'notifications/?$', views.notifications, name='notifications'),
	url(r'notifications/friend_requests/?$', views.friend_requests, name='friend-requests'),
	url(r'notifications/set_read$', views.notification_setread, name='set-read'),
	url(r'notifications/(?P<notification>'+ uuidr +'+)\.rm$', views.notification_delete, name='notification-delete'),

	# User meta + messages
	url(r'activity/?$', views.activity_feed, name='activity'),
	url(r'users.search$', views.user_search, name='user-search'),
	url(r'pref$', views.prefs, name='prefs'),
	url(r'settings/profile$', views.profile_settings, name='profile-settings'),
	url(r'messages/?$', views.messages, name='messages'),
	url(r'messages/(?P<message>'+ uuidr +'+)/rm$', views.message_rm, name='message-delete'),
	url(r'messages/'+ username +'$', views.messages_view, name='messages-view'),
	url(r'messages/'+ username +'/read$', views.messages_read, name='messages-read'),

	# Help/configuration
	url(r'lights$', views.set_lighting, name='set-lighting'),
	url(r'complaints$', views.help_complaint, name='complaints'),
	url(r'server$', views.server_stat, name='server-stat'),
	url(r'help/rules/?$', views.help_rules, name='help-rules'),
	url(r'help/faq/?$', views.help_faq, name='help-faq'),
	url(r'help/legal/?$', views.help_legal, name='help-legal'),
	url(r'help/contact/?$', views.help_contact, name='help-contact'),
	url(r'help/login/?$', views.help_login, name='help-login'),
	url(r'help/whatads/?$', views.whatads, name='what-ads'),
	url(r'why/?$', views.help_why, name='help-why'),

	# Manage
	url(r'man/?$', views.admin_index, name='admin-index'),
	url(r'man/users$', views.admin_users, name='admin-users'),
	url(r'man/users_list$', views.users_list, name='users-list'),


	# "API"
	url(r'posts.json$', views.post_list, name='post-list'),

	# Util, right now we are away from the primary appo
	url(r'origin$', views.origin_id, name='origin-id-get'),
	# :^)
	#url(r'openverse.png', views.openverse_logo, name='openverse-logo'),
	url(r'debug/' + username + '$', views.debug, name='rickroll'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

closedverse_main/views.py
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseBadRequest,  HttpResponseServerError, HttpResponseForbidden, JsonResponse
from django.template import loader
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError
from django.db.models import Q, Count, Exists, OuterRef
from .models import *
from .util import *
from .serializers import CommunitySerializer
from closedverse import settings
import re
from django.urls import reverse
from random import getrandbits
from random import choice
from json import dumps, loads
import sys, traceback
import subprocess
from datetime import datetime
import django.utils.dateformat
from binascii import hexlify
from os import urandom

#from silk.profiling.profiler import silk_profile

def json_response(msg='', code=0, httperr=400):
	thing = {
	# success would be false, but 0 is faster I think (Miiverse used 0 because Perl doesn't have bools)
	# it also should be removed
	'success': 0,
	'errors': [
			{
			# We should drop this Miiverse formatting at some point
			'message': msg,
			'error_code': code,
			}
		],
	'code': httperr,
	}
	return JsonResponse(thing, safe=False, status=httperr)

def community_list(request):
	"""Lists communities / main page."""
	if 'json' in request.META.get('HTTP_ACCEPT', ''):
		cs = CommunitySerializer
		response = {
			'general': cs.many(Community.objects.filter(type=0).order_by('-created')),
			'game': cs.many(Community.objects.filter(type=1).order_by('-created')),
			'special': cs.many(Community.objects.filter(type=2).order_by('-created'))
		}
		return JsonResponse(response)
	obj = Community.objects
	if request.user.is_authenticated:
		classes = ['guest-top']
		favorites = request.user.community_favorites()
	else:
		classes = []
		favorites = None
	availableads = Ads.ads_available()
	if(availableads):
		ad = Ads.get_one()
	else:
		ad = "no ads"
	return render(request, 'closedverse_main/community_list.html', {
		'title': 'Communities',
		'ad': ad,
		'availableads': availableads,
		'classes': classes,
		'general': obj.filter(type=0).order_by('-created')[0:8],
		'game': obj.filter(type=1).order_by('-created')[0:8],
		'special': obj.filter(type=2).order_by('-created')[0:8],
		'feature': obj.filter(is_feature=True).order_by('-created'),
		'favorites': favorites,
		'settings': settings,
		'ogdata': {
				'title': 'Community List',
				'description': "closedverse rehost my god",
				'date': 'None',
				'image': request.build_absolute_uri(settings.STATIC_URL + 'img/favicon.png'),
			},
	})
def community_all(request):
	"""All communities, with pagination"""
	try:
		offset = int(request.GET.get('offset', '0'))
	except ValueError:
		offset = 0
	if request.user.is_authenticated:
		classes = ['guest-top']
	else:
		classes = []
	gen = Community.get_all(0, offset)
	game = Community.get_all(1, offset)
	special = Community.get_all(2, offset)
	if gen.count() > 11 or game.count() > 11 or special.count() > 11:
		has_next = True
	else:
		has_next = False
	if gen.count() < 1 or game.count() < 1:
		has_back = True
	else:
		has_back = False
	back = offset - 12
	next = offset + 12
	return render(request, 'closedverse_main/community_all.html', {
		'title': 'All Communities',
		'classes': classes,
		'general': gen,
		'game': game,
		'special': special,
		'has_next': has_next,
		'next': next,
	})

def community_search(request):
	"""Community searching"""
	query = request.GET.get('query')
	if not query or len(query) < 2:
		raise Http404()
	if request.GET.get('offset'):
		communities = Community.search(query, 20, int(request.GET['offset']), request)
	else:
		communities = Community.search(query, 20, 0, request)
	if communities.count() > 19:
		if request.GET.get('offset'):
			next_offset = int(request.GET['offset']) + 20
		else:
			next_offset = 20
	else:
		next_offset = None
	return render(request, 'closedverse_main/community-search.html', {
		'classes': ['search'],
		'query': query,
		'communities': communities,
		'next': next_offset,
	})

@login_required
def community_favorites(request):
	"""Favorite communities, can be used for self by default or other users"""
	user = request.user
	has_other = False
	if request.GET.get('u'):
		user = get_object_or_404(User, username=request.GET['u'])
		has_other = True
		profile = user.profile()
		profile.setup(request)
		communities = user.community_favorites(True)
	else:
		communities = request.user.community_favorites(True)
		profile = user.profile()
		profile.setup(request)
	return render(request, 'closedverse_main/community_favorites.html', {
		'title': 'Favorite communities',
		'favorites': communities,
		'user': user,
		'profile': profile,
		'other': has_other,
	})

def login_page(request):
	"""Login page! using our own user objects."""
	# Redirect the user to / if they're logged in, forcing them to log out
	if request.user.is_authenticated:
		return redirect('/')
	if request.method == 'POST':
		# If we don't have all of the POST parameters we want..
		if not (request.POST['username'] and request.POST['password']):
		# then return that.
			return HttpResponseBadRequest("You didn't fill in all of the fields.")
		# Now let's authenticate.
		# Wait, first check if the user exists. Remove spaces from the username, because some people do that.
		# Hold up, first we need to check proxe.
		# Never mind
		"""
		if settings.PROD:
			if iphub(request.META['REMOTE_ADDR']):
				spamuser = True
				if settings.disallow_proxy:
					# This was for me, a server error will email admins of course.
					raise ValueError
		"""
		user = User.objects.authenticate(username=request.POST['username'], password=request.POST['password'])
		# None = doesn't exist, False = invalid password.
		if user is None:
			return HttpResponseNotFound("The user doesn't exist.")
		else:
			# Todo: I might want to do some things relating to making models take care of object stuff like this instead of the view, it's totally messed up now.
			successful = False if user[1] is False or not user[0].is_active() else True
			LoginAttempt.objects.create(user=user[0], success=successful, addr=request.META.get('REMOTE_ADDR'))
			if user[1] is False:
				return HttpResponse("Invalid password.", status=401)
			elif user[1] is 2:
				return HttpResponse("This account's password needs to be reset. Contact an admin or reset by email.", status=400)
			elif not user[0].is_active():
				return HttpResponseForbidden("This account was disabled.")
		request.session['passwd'] = user[0].password
		login(request, user[0])

		# Then, let's get the referrer and either return that or the root.
		# Actually, let's not for now.
		#if request.META['HTTP_REFERER'] and "login" not in request.META['HTTP_REFERER'] and request.META['HTTP_HOST'] in request.META['HTTP_REFERER']:
		#	location = request.META['HTTP_REFERER']
		#else:
		location = '/'
		if request.GET.get('next'):
			location = request.GET['next']
		return HttpResponse(location)
	else:
		return render(request, 'closedverse_main/login_page.html', {
			'title': 'Log in',
			#'classes': ['no-login-btn']
		})
def signup_page(request):
	"""Signup page, lots of checks here"""
	# Redirect the user to / if they're logged in, forcing them to log out
	if request.user.is_authenticated:
		return redirect('/')
	if request.method == 'POST':
		if settings.recaptcha_pub:
			if not recaptcha_verify(request, settings.recaptcha_priv):
				return HttpResponse("The reCAPTCHA validation has failed.", status=402)
		if not (request.POST.get('username') and request.POST.get('password') and request.POST.get('password_again')):
			return HttpResponseBadRequest("You didn't fill in all of the required fields.")
		if not re.compile(r'^[A-Za-z0-9-._]{1,32}$').match(request.POST['username']) or not re.compile(r'[A-Za-z0-9]').match(request.POST['username']):
			return HttpResponseBadRequest("Your username either contains invalid characters or is too long (only letters + numbers, dashes, dots and underscores are allowed")
		if settings.PROD:
			for keyword in ['admin', 'admln', 'adrnin', 'admn', ]:
				if keyword in request.POST['username'].lower():
					return HttpResponseForbidden("You aren't funny. Please use a funny name.")
		conflicting_user = User.objects.filter(Q(username__iexact=request.POST['username']) | Q(username__iexact=request.POST['username'].replace(' ', '')))
		if conflicting_user:
			return HttpResponseBadRequest("A user with that username already exists.")
		if not request.POST['password'] == request.POST['password_again']:
			return HttpResponseBadRequest("Your passwords don't match.")
		if not (request.POST['nickname'] or request.POST['origin_id']):
			return HttpResponseBadRequest("You didn't fill in an NNID, so you need a nickname.")
		if request.POST['nickname'] and len(request.POST['nickname']) > 32:
			return HttpResponseBadRequest("Your nickname is either too long or too short (1-32 characters)")
		if request.POST['origin_id'] and (len(request.POST['origin_id']) > 16 or len(request.POST['origin_id']) < 6):
			return HttpResponseBadRequest("The NNID provided is either too short or too long.")
		if request.POST.get('email'):
			if User.email_in_use(request.POST['email']):
				return HttpResponseBadRequest("That email address is already in use, that can't happen.")
			try:
				EmailValidator()(value=request.POST['email'])
			except ValidationError:
				return HttpResponseBadRequest("Your e-mail address is invalid. Input an e-mail address, or input nothing.")
		check_others = Profile.objects.filter(user__addr=request.META['REMOTE_ADDR'], let_freedom=False).exists()
		if check_others:

closedverse_main/templates/closedverse_main/community_list.html
{% extends "closedverse_main/layout.html" %}
{% load closedverse_tags %}{% load closedverse_community %}{% block main-body %}
<div class="community-main">
		<div id="community-eyecatch"></div>
	</div>
	<div class="community-top-sidebar">
		<form action="{% url "main:community-search" %}" class="search">
			<input maxlength="32" name="query" placeholder="Search all communities" type="text"><input title="Search" type="submit" value="q">
		</form>
		<div id="identified-user-banner">
			<a class="list-button pf2m-icon" href="/communities/2"><span class="title">Get the latest news here!</span><span class="text">Posts from Verified Users</span></a>
		</div>
		{% if settings.memo_title and settings.memo_msg %}
		<div class="post-list-outline index-memo">
			<h2 class="label">{{ settings.memo_title }}</h2>
			{% autoescape off %}{{ settings.memo_msg }}{% endautoescape %}
             		<h2>What is Blueverse?</h2>
			{% autoescape off %}{{ settings.memo_msg1 }}{% endautoescape %}
             		<h2>Who's the owner?</h2>
			{% autoescape off %}{{ settings.memo_msg2 }}{% endautoescape %}
            		<h2>It is Closedverse-based? It looks like Closedverse.</h2>
			{% autoescape off %}{{ settings.memo_msg3 }}{% endautoescape %}
            		<h2>Is there any rules?</h2>
			{% autoescape off %}{{ settings.memo_msg4 }}{% endautoescape %}
            		<h2>Is my personal data in danger if I sign up to this website?</h2>
			{% autoescape off %}{{ settings.memo_msg5 }}{% endautoescape %}
			        <h2>Why this is in closed beta?</h2>
			<p>Well, it's in closed beta because some things aren't complete and this clone isn't ready yet...</p>

		</div>
		{% endif %}
		{% if availableads %}
			<div class="adx">
				<h3 class="community-title">User-Generated Ad</h3>
                <p class="community-title"><a href="/help/whatads">What are user-generated ads?</a></p>
                <p class="community-title">If you think that this ad doesn't need to be here, contact Rixy</p>
				<a href="{{ ad.url }}"><img src="{{ ad.imageurl }}"></a>
			</div>
		{% endif %}
	</div>
	<div class="community-main">
	{% if favorites %}
		<h3 class="community-title symbol community-favorite-title">Favorite communities</h3>
		<div class="card" id="community-favorite">
		  <ul>
			{% for favorite in favorites %}
				<li class="test-favorite-community">
				  <a href="{% url "main:community-view" favorite.id %}" class="icon-container">
					<img src="{{ favorite.icon }}" class="icon">

				  </a>
				</li>
			 {% endfor %}

			<li class="read-more">
			  <a href="{% url "main:community-favorites" %}" class="favorite-community-link symbol"><span class="symbol-label">Show more</span></a>
			</li>
		  </ul>
		</div>
	{% endif %}
		{% if feature %}
			{% community_page_element feature "Featured Communities" True %}
		{% endif %}
			{% community_page_element general "General Communities" %}
			{% community_page_element game "Game Communities" %}
			{% community_page_element special "Special Communities" %}
			<a href="{% url "main:community-viewall" %}" class="big-button">Show more</a>
	</div>
	<div id="community-guide-footer">
		<div id="guide-menu">
			<a class="arrow-button" href="{% url "main:help-why" %}"><span>Why join?</span></a>
			<a class="arrow-button" href="{% url "main:help-rules" %}"><span>Blueverse Rules</span></a>
			<a class="arrow-button" href="{% url "main:help-faq" %}"><span>Frequently Asked Questions (FAQ)</span></a>
			<a class="arrow-button" href="{% url "main:what-ads" %}"><span>What are user-generated ads?</span></a>
			{% if settings.PROD %}
			{% endif %}
		</div>
	</div>
{% endblock %}

closedverse_main/templates/closedverse_main/layout.html
{% load static %}{% load closedverse_tags %}{% block html %}{% if not request.META.HTTP_X_PJAX %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
	{% endif %}
    <title>{% if title %}{{ title }} - Blueverse{% else %}Blueverse{% endif %}</title>
    {% if not request.META.HTTP_X_PJAX %}
	<meta http-equiv="content-style-type" content="text/css">
    <meta http-equiv="content-script-type" content="text/javascript">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-title" content="Blueverse">
    <meta name="description" content="Welcome to Blueverse.">
	<meta property="og:locale" content="en_US">
	{% if ogdata %}
		<meta property="og:title" content="{{ ogdata.title }}">
		<meta property="og:type" content="article">
		<meta property="og:url" content="{{ request.build_absolute_uri }}">
		<meta property="og:image" content="{{ ogdata.image }}">
		<meta property="og:description" content="{{ ogdata.description|truncatechars:150 }}">
		<meta property="og:site_name" content="Blueverse">
		<meta property="article:published_time" content="{{ ogdata.date }}">
	{% endif %}
	<link rel="shortcut icon" type="image/png" href="{% static "img/favicon.png" %}">
    <link rel="stylesheet" type="text/css" href="{% static "closedverse.css" %}">
	<link id="darkness" {% if request.session.lights %}disabled {% endif %}rel="stylesheet" type="text/css" href="{% static "blueness.css" %}">
	<script src="{% static "jslibs.js" %}"></script>
    <script src="{% static "closedverse.js" %}"></script>
  </head>

  <body class=""{% if request.user.is_authenticated %}
  sess-usern="{{ request.user.username }}"
  {% endif %}>
    <div id="wrapper"{% if not request.user.is_authenticated %} class="guest"{% endif %}>
      <div id="sub-body">
        <menu id="global-menu">
          <li id="global-menu-logo"><h1><a href="/"><img src="{% static "img/menu-logo.png" %}" alt="Blueverse"></a></h1></li>
		  {% if request.user.unique_id %}
          <li id="global-menu-list">
            <ul>
              <li id="global-menu-mymenu"><a href="{% url "main:user-view" request.user.username %}"><span class="icon-container {% user_class request.user %}"><img src="{% avatar request.user %}" alt="My Profile"></span><span>My Profile</span></a></li>
			  <li id="global-menu-feed"><a href="{% url "main:activity" %}" class="symbol"><span>Activity Feed</span></a></li>
              <li id="global-menu-community"><a href="/" class="symbol"><span>Communities</span></a></li>
			  <li id="global-menu-message"><a href="{% url "main:messages" %}" class="symbol"></a></li>
			  <li id="global-menu-news"><a href="{% url "main:notifications" %}" class="symbol"></a></li>
              <li id="global-menu-my-menu"><button class="symbol js-open-global-my-menu open-global-my-menu"></button>
                <menu id="global-my-menu" class="invisible none">
                  <li><a href="{% url "main:profile-settings" %}" class="symbol my-menu-profile-setting"><span>Profile settings</span></a></li>
                  <li><a href="#" class="symbol my-menu-account-setting"><span>Account preferences</span></a></li>
                  <li><a href="{% url "main:special-community-tag" "announcements" %}" class="symbol my-menu-openman"><span>Blueverse Announcements</span></a></li>
                  <li><a href="{% url "main:help-faq" %}" class="symbol my-menu-guide"><span>Frequently Asked Questions (FAQ)</span></a></li>
				  <li><a href="{% url "main:help-rules" %}" class="symbol my-menu-guide"><span>Blueverse Rules</span></a></li>
				    <li><a href="#" class="symbol my-menu-white-power"><span>Feedback/bug report</span></a></li>
                  <li><a href="{% url "main:server-stat" %}" class="symbol my-menu-openman"><span>Server Statistics</span></a></li>
				  <li>
                    <form action="{% url "main:logout" %}" method="post" id="my-menu-logout" class="symbol">
                      {% csrf_token %}
                      <input type="submit" value="Log out">
                    </form>
                  </li>
                </menu>
              </li>
            </ul>
          </li>
		  {% else %}
		  <li id="global-menu-login">
            <a href="{% url "main:login" %}" class="login">
              <input type="image" alt="Sign in" src="{% static "img/sign-in.png" %}">
            </a>
          </li>
		  {% endif %}
        </menu>
      </div>
	  <div id="container">
	  {% endif %}
      <div id="main-body"
    class="{% if classes %}{{ classes|join:" " }} {% endif %}{% if not request.user.is_authenticated %}
	guest{% endif %}"
	csrf-token="{{ csrf_token }}">
	  {% block main-body %}
	  {% endblock %}
      </div>
	  {% if not request.META.HTTP_X_PJAX %}
	  </div>
      <div id="footer">
        <div id="footer-inner">
          <div class="link-container">
			<p><a href="/help/contact">Contact</a> <a href="/help/rules">Rules</a> <a href="/why">Why should I join?</a><a href="https://github.com/Rix565/Blueverse">Source code</a></p>
			<p id="copyright"><a href="https://nintendo.com/">Inspired by Hatena Co, Ltd/Nintendo's Miiverse. Blueverse don't nor wish make money from it. Please support them instead!</a><br>
			<p id="copyright">Blueverse, 2021</p>
			</div>
        </div>
      </div>
    </div>
  </body>
</html>
{% endif %}{% endblock html %}

closedverse_main/templates/closedverse_main/messages.html
{% extends "closedverse_main/layout.html" %}
{% load static %}{% load closedverse_tags %}{% load closedverse_user %}
{% block main-body %}
{% user_sidebar request user user.profile 0 True %}
<div class="main-column messages">
  <div class="post-list-outline">

    <h2 class="label">Messages
		<span class="message-chk">
			<input type="checkbox" name="online" value="{% if request.session.messages_online %}n{% else %}1{% endif %}"{% if request.session.messages_online %} checked{% endif %}> Only show online friends
		</span>
	</h2>
	<!--
	{% if friends %}
		<form class="friend-search search" action="{% url "main:messages" %}">
			<input type="text" name="query" title="Search friends" placeholder="Search friends" minlength="2" maxlength="16">
			<input type="submit" value="q" title="Search">
		</form>
	{% endif %}
	-->
	<div class="list">
		{% if friends %}
				<ul class="list-content-with-icon-and-text arrow-list" data-next-page-url="{% if next %}?offset={{ next }}{% endif %}">
		{% for friend in friends %}
					<li class="trigger{% if not friend.get_latest_msg.mine and friend.get_latest_msg.read == False %} notify{% endif %}" data-href="{% url "main:messages-view" friend.username %}">
						{% user_icon_container friend 0 True %}

					  <div class="body">
						<p class="title">
						  <span class="nick-name"><a {% if friend.color %}style=color:{{ friend.color }}{% endif %} href="{% url "main:user-view" friend.username %}">{{ friend.nickname }}</a></span>
						  <span class="id-name">{{ friend.username }}</span>
						</p>
						{% if friend.get_latest_msg %}
						<span class="timestamp">{% time friend.get_latest_msg.created %}</span>
						<p class="text {% if friend.get_latest_msg.drawing or friend.get_latest_msg.is_rm %}type-memo {% endif %}{% if friend.get_latest_msg.mine %}my{% else %}other{% endif %}">{{ friend.get_latest_msg.trun }}</p>
						{% else %}
						<p class="text placeholder">You haven't exchanged messages with this user yet.</p>
						{% endif %}

					  </div>
					</li>
		{% endfor %}
			</ul>
	{% else %}
		{% nocontent "You don't have any friends yet." %}
	{% endif %}
	</div>
  </div>
</div>
{% endblock %}